### ISSUE TITLE
iOS 14 beta 7

### ISSUE THREAD

**Issue by hcarrega** [stayawayinesctec/stayaway-app#45] opened 2020-08-29 14:05 UTC
No logs and app not show never updated ![image](https://user-images.githubusercontent.com/2180184/91638660-fe946f00-ea08-11ea-919d-07136c127ab0.png)
![image](https://user-images.githubusercontent.com/2180184/91638670-09e79a80-ea09-11ea-840f-373f6c7c5255.png)

**Comment by hcarrega** [comment] 2020-08-29 14:06
On two iPhones on oficial build 9 exposures are show

**Comment by hcarrega** [comment] 2020-09-03 15:50
I will install when new version it's out , right now is useless

**Comment by fmaia** [comment] 2020-09-07 14:51
Version 1.0.1 should solve this issue. Could you please update and check if it does so?

**Comment by hcarrega** [comment] 2020-09-07 15:38
New version installed seems fine now

**Comment by fmaia** [comment] 2020-09-07 15:44
Closing the issue then.

**Comment by hcarrega** [comment] 2020-09-08 11:07
Exposure logs still update but not in the app... still have 6/9/2020

**Comment by marado** [comment] 2020-09-08 11:24
There is a new fix for iOS >= 13.7 on dp3t-sdk-ios's HEAD: https://github.com/DP-3T/dp3t-sdk-ios/pull/210

**Comment by hcarrega** [comment] 2020-09-08 11:26
Waiting for update

**Comment by fmaia** [comment] 2020-09-08 11:31
@hcarrega just to clarify the issue, what happened was that updating to the latest beta got you back to a non-updating state or you attempted the same solution on a different phone and the issue remained? Thank you.

**Comment by hcarrega** [comment] 2020-09-08 11:38
Same on iPhone SE 2020 , normally I use two phones daily both on same version mirror from other

**Comment by fmaia** [comment] 2020-09-08 11:41
> There is a new fix for iOS >= 13.7 on dp3t-sdk-ios's HEAD: [DP-3T/dp3t-sdk-ios#210](https://github.com/DP-3T/dp3t-sdk-ios/pull/210)

@marado thank you for pointing this out but this fix should be unrelated with the issue discussed here. It concerns how the system behaves after users mark themselves as infected. The issue here is related with how the app checks for exposures and how it behaves when it is not able to do it successfully, which typically happens when the exposure check limit has been reached.

**Comment by fmaia** [comment] 2020-09-08 11:44
@hcarrega so in both worked with beta 6 and not with beta 7? If the update occurred recently the 24h period for the new update is again valid. 
There is, however, a parallel issue (solved but that did not make it into 1.0.1) that might lead to this behaviour. Could you check if, after 24h, quitting the app entirely (even in the app switcher) and opening it again fixes the issue? Thank you.

**Comment by hcarrega** [comment] 2020-09-08 11:49
in other words, the app wasn't even giving me until the most recent update.  it was giving update done on the 6th, since then in the exposure part it is updating but not in the app frontend.  I've done kill a few times and even rebooted too

**Comment by fmaia** [comment] 2020-09-08 11:52
Ok, thank you. We'll try to reproduce this on our side and look into it. Reopening the issue.

**Comment by hcarrega** [comment] 2020-09-08 11:54
![image](https://user-images.githubusercontent.com/2180184/92473257-5e8dd100-f1d2-11ea-9eee-b2d75d269fd3.png)
![image](https://user-images.githubusercontent.com/2180184/92473280-651c4880-f1d2-11ea-85ca-9be712d74d97.png)

**Comment by hcarrega** [comment] 2020-09-08 14:08
iPhone 8 update minutos ago for today ... waiting for iPhone SE 2020

**Comment by hcarrega** [comment] 2020-09-08 18:05
@fmaia how many api calls a phone can made ?

**Comment by davipt** [comment] 2020-09-10 22:07
I can confirm the v1.0.0 never updated any keys from the server on any iOS beta but updating to 1.0.1 fixed it, or at least improved it. For example iOS tells me there was an update today 10th at 19h but the app still says it was updated yesterday 9.9.2020. 
With 1.0.0 I did not see anything in particular on the console logs. It just felt it never wanted to do the server request to download the keys from others. I’ve installed at the same time on iOS 13 latest official and non beta on my wife and it worked correctly there. Whatever it was it is related to iOS 14 beta and I’ve seen other apps also suffering from connectivity issues during the beta phase. 
In case of doubt, if it never updates, fully remove the app and reinstall it. I also suspect it may be broken permissions, which is a common occurrence on iOS beta updates (eg the app thinks it has eg location permissions, and settings states the same, but the system things otherwise, and it may be enough to turn permissions off and on, or may need a full cycle of reinstall and enable permissions from scratch. 
It’s a beta (iOS). Anything can happen.

**Comment by fmaia** [comment] 2020-09-15 15:11
There are some issues in iOS beta versions that we are still investigating and as @davipt pointed out, in beta versions all kinds of things may happen. Nevertheless, today v1.0.2 is being released. Please check if you see improvements. A 24h window should be allowed after the update for the app to update its status. Thank you.

**Comment by hcarrega** [comment] 2020-09-16 05:13
iOS 14 GM is out since yesterday ,no much changes for now app is working fine

**Comment by fmaia** [comment] 2020-09-18 10:37
Thank you. I'm closing the issue since iOS 14 has been released and the problem seems to have been solved.

**Closed by fmaia** 2020-09-18 10:37 UTC
